version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Asia/Jerusalem"
    open-pull-requests-limit: 15
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
