apiVersion: v2
name: datafy-agent
version: 3.3.1
appVersion: 11.36.1_1.4.1
home: https://datafy.io
maintainers:
  - name: Datafy.io, Inc. All Rights Reserved.
    url: https://github.com/datafy-io/datafy-agent-helm
