apiVersion: v2
name: datafy-agent
version: 3.0.0
appVersion: 1.31.15_1.1.2_1.0.0
home: https://datafy.io
maintainers:
  - name: Datafy.io, Inc. All Rights Reserved.
    url: https://github.com/datafy-io/datafy-agent-helm
