## @param awsEbsCsiDriver.enabled to install aws-ebs-csi-driver chart as well
awsEbsCsiDriver:
  enabled: false

## @param extraLabels Labels to add to all deployed objects
##
extraLabels: {}
## @param extraAnnotations Annotations to add to all deployed objects
##
extraAnnotations: {}

## @param agent.token Datafy agent token
## @param agent.mode The mode of agent to install. Valid values: "Sensor", "AutoScaler"
## @param agent.env Environment variables to add to datafy-agent daemon set
##
agent:
  token:
  mode: AutoScaler
  dsoUrl: wss://dso.datafy.io
  env: { }

  ## @param agent.tokenSecret.name The name of the secret containing the token
  ## @param agent.tokenSecret.key The key within the secret that contains the token
  tokenSecret:
    name: datafy-token
    key: token

    ## @param agent.tokenSecret.external Configuration for fetching the token from ExternalSecret
    ## Ref: https://external-secrets.io/
    ##
    ## @param agent.tokenSecret.external.remoteKey The name of the key in the external secret store. If set, the external secret will be used.
    ## @param agent.tokenSecret.external.create Whether to create ExternalSecret resources
    ## @param agent.tokenSecret.external.name The name of the ExternalSecret containing the token
    ## @param agent.tokenSecret.external.secretStoreRef.name The name of the secret store
    ## @param agent.tokenSecret.external.secretStoreRef.kind The kind of the secret store. Valid values: "SecretStore", "ClusterSecretStore"
    external:
      remoteKey:
      create: false
      name: datafy-token
      secretStoreRef:
        name: aws-secret-store
        kind: ClusterSecretStore

  coreMockEnabled: false
  hqMockEnabled: false

  ## @param agent.affinity Affinity for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
                  - auto
                  - hybrid
  ## @param agent.nodeSelector Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  ##
  nodeSelector: { }
  ## @param agent.tolerations Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations:
    - operator: "Exists"

  securityContext:
    privileged: true
    runAsUser: 1000
    runAsGroup: 1000

  image:
    pullPolicy: Always
    repository: public.ecr.aws/datafy-io/datafy-agent
    tag: latest

    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## imagePullSecrets:
    ##   - myRegistryKeySecretName
    ##
    imagePullSecrets: []

ebsCsiProxy:
  enabled: true
  namespace:
  image:
    pullPolicy: IfNotPresent
    repository: public.ecr.aws/datafy-io/ebs-csi-controller
    tag: latest
