apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceanchors.datafy.io
spec:
  group: datafy.io
  names:
    kind: ResourceAnchor
    listKind: ResourceAnchorList
    plural: resourceanchors
    singular: resourceanchor
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: ResourceAnchor is a cluster-scoped resource that represents an anchor for resources created cross namespace by Datafy.
      subresources:
        status: { }
