apiVersion: v1
kind: ConfigMap
metadata:
  name: datafy-agent-envvars
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.agent.env }}{{ toYaml . | nindent 2 }}{{- end }}
