apiVersion: v1
kind: ConfigMap
metadata:
  name: datafy-agent-envvars
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datafy-agent
    {{- with .Values.extraLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.extraAnnotations }}{{ toYaml . | nindent 4 }}{{- end }}
data:
  {{- with .Values.agent.env }}{{ toYaml . | nindent 2 }}{{- end }}
