{{- $name := "datafy-controller-webhook" }}
{{- $fqdn := printf "%s.%s.svc" $name .Release.Namespace }}
{{- $ca := genSelfSignedCert $fqdn (list) (list $fqdn $name (printf "%s.%s" $name .Release.Namespace)) 365 }}
kind: Secret
apiVersion: v1
metadata:
  name: datafy-controller-webhook-tls
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  {{- with .Values.extraAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc (trim $ca.Cert) }}
  tls.key: {{ b64enc (trim $ca.Key) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: datafy-controller-webhook
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  {{- with .Values.extraAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: datafy-controller.datafy.io
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    reinvocationPolicy: IfNeeded
    failurePolicy: Fail
    timeoutSeconds: 5
    matchPolicy: Equivalent
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods" ]
        scope: "*"
    objectSelector:
      matchExpressions:
        - key: "datafy.io/install"
          operator: Exists
        - key: "app"
          operator: In
          values: [ "ebs-csi-node", "ebs-csi-controller" ]
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: datafy-controller-webhook
        path: /mutate-v1-pods
        port: 443
      caBundle: {{ b64enc (trim $ca.Cert) }}
