{{- if eq .Values.agent.mode "AutoScaler" }}
{{- if .Values.ebsCsiProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datafy-csi-patcher-sa
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datafy-csi-patcher-clusterrole
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "daemonsets" ]
    resourceNames: [ "ebs-csi-controller", "ebs-csi-node" ]
    verbs: [ "get", "list", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datafy-csi-patcher-clusterrolebinding
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: datafy-csi-patcher-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: datafy-csi-patcher-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
