{{- if .Values.csi.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: datafy-agent-patch-csi
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: datafy-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: datafy-agent-patch-csi
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: datafy-agent
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: csi-patcher
          image: bitnami/kubectl:latest
          env:
            - name: K8S_CSI_NAMESPACE
              value: {{ default "kube-system" .Values.csi.namespace }}
            - name: K8S_CSI_VERSION
              value: {{ default "latest" .Values.csi.version }}
            {{- if .Values.csi.iacUrl }}
            - name: IAC_URL
              value: {{ .Values.csi.iacUrl }}
            {{- end }}
          command:
            - /bin/sh
            - -c
            - |
{{ .Files.Get "files/patch-csi.sh" | indent 14 }}
      restartPolicy: Never
      serviceAccountName: datafy-csi-patcher-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: datafy-agent-unpatch-csi
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: datafy-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: datafy-agent-unpatch-csi
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: datafy-agent
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: csi-unpatcher
          image: bitnami/kubectl:latest
          env:
            - name: K8S_CSI_NAMESPACE
              value: {{ default "kube-system" .Values.csi.namespace }}
          command:
            - /bin/sh
            - -c
            - |
{{ .Files.Get "files/unpatch-csi.sh" | indent 14 }}
      restartPolicy: Never
      serviceAccountName: datafy-csi-patcher-sa
{{- end }}
