{{- if .Values.ebsCsiProxy.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: datafy-agent-patch-csi
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: datafy-agent-patch-csi
      labels:
        {{- include "datafy-agent.labels" . | nindent 8 }}
    spec:
      containers:
        - name: csi-patcher
          image: bitnami/kubectl:latest
          env:
            - name: K8S_CSI_NAMESPACE
              value: {{ include "datafy-agent.ebsCsiProxyNamespace" . }}
            - name: K8S_CSI_IMAGE
              value: {{ printf "%s:%s" .Values.ebsCsiProxy.image.repository .Values.ebsCsiProxy.image.tag | quote }}
            {{- with .Values.ebsCsiProxy.iacUrl }}
            - name: IAC_URL
              value: {{ . }}
            {{- end }}
          command:
            - /bin/sh
            - -c
            - |
{{ .Files.Get "files/patch-csi.sh" | indent 14 }}
      restartPolicy: Never
      serviceAccountName: datafy-csi-patcher-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: datafy-agent-unpatch-csi
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: datafy-agent-unpatch-csi
      labels:
        {{- include "datafy-agent.labels" . | nindent 8 }}
    spec:
      containers:
        - name: csi-unpatcher
          image: bitnami/kubectl:latest
          env:
            - name: K8S_CSI_NAMESPACE
              value: {{ include "datafy-agent.ebsCsiProxyNamespace" . }}
          command:
            - /bin/sh
            - -c
            - |
{{ .Files.Get "files/unpatch-csi.sh" | indent 14 }}
      restartPolicy: Never
      serviceAccountName: datafy-csi-patcher-sa
{{- end }}
