apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datafy-agent
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datafy-agent
    {{- with .Values.extraLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.extraAnnotations }}{{ toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: datafy-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: datafy-agent
    spec:
      {{- if .Values.datafy.affinity }}
      affinity:
        {{- with .Values.datafy.affinity }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- end }}
      {{- if .Values.datafy.nodeSelector }}
      nodeSelector:
        {{- with .Values.datafy.nodeSelector }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- end }}
      {{- if .Values.datafy.tolerations }}
      tolerations:
        {{- with .Values.datafy.tolerations }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- end }}
      containers:
        {{- $enableCoreMock := or .Values.datafy.coreMockEnabled .Values.datafy.discoveryOnly }}
        {{- if not $enableCoreMock }}
        - name: core
          args: [ core ]
          image: "{{ .Values.image.registry }}/{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: datafy-agent-envvars
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
        {{- end }}
        - name: shell
          args: [ shell ]
          image: "{{ .Values.image.registry }}/{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: datafy-agent-envvars
          env:
            - name: DATAFY_GRPC_ENABLED
              value: "true"
            - name: DATAFY_GRPC_ADDRESS
              value: "unix:/run/datafy/datafy-agent.sock"
            - name: DATAFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datafy-token
                  key: token
            {{- if .Values.datafy.hqMockEnabled }}
            - name: DATAFY_MOCKS_HQ_ENABLED
              value: {{ .Values.datafy.hqMockEnabled | quote }}
            {{- end }}
            {{- if $enableCoreMock }}
            - name: DATAFY_MOCKS_CORE_ENABLED
              value: {{ $enableCoreMock | quote }}
            {{- end }}
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range $secret := .Values.image.pullSecrets }}
        - name: {{ $secret }}
        {{ end }}
      {{- end }}
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      hostPID: true
      hostNetwork: true
