{{- $enableCoreMock := or .Values.agent.coreMockEnabled (eq .Values.agent.mode "Sensor") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datafy-agent
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: datafy-agent
  template:
    metadata:
      labels:
        app: datafy-agent
        {{- include "datafy-agent.labels" . | nindent 8 }}
    spec:
      {{- if .Values.agent.affinity }}
      affinity:
        {{- with .Values.agent.affinity }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- end }}
      {{- if .Values.agent.nodeSelector }}
      nodeSelector:
        {{- with .Values.agent.nodeSelector }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- end }}
      {{- if .Values.agent.tolerations }}
      tolerations:
        {{- with .Values.agent.tolerations }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- end }}
      containers:
        {{- if not $enableCoreMock }}
        - name: core
          args: [ core ]
          image: {{ printf "%s:%s" .Values.agent.image.repository .Values.agent.image.tag }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          {{- with .Values.agent.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: datafy-agent-envvars
          env:
            - name: DATAFY_DSO_URL
              value: {{ .Values.agent.dsoUrl }}
            - name: DATAFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datafy-token
                  key: token
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
        {{- end }}
        - name: shell
          args: [ shell ]
          image: {{ printf "%s:%s" .Values.agent.image.repository .Values.agent.image.tag }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          {{- with .Values.agent.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: datafy-agent-envvars
          env:
            - name: DATAFY_GRPC_ENABLED
              value: "true"
            - name: DATAFY_DSO_URL
              value: {{ .Values.agent.dsoUrl }}
            - name: DATAFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datafy-token
                  key: token
            {{- if .Values.agent.hqMockEnabled }}
            - name: DATAFY_MOCKS_HQ_ENABLED
              value: {{ .Values.agent.hqMockEnabled | quote }}
            {{- end }}
            {{- if $enableCoreMock }}
            - name: DATAFY_MOCKS_CORE_ENABLED
              value: {{ $enableCoreMock | quote }}
            {{- end }}
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      {{- if .Values.agent.image.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.agent.image.imagePullSecrets }}
        - name: {{ . }}
        {{ end }}
      {{- end }}
      hostPID: true
      hostNetwork: true
