# The controller hashes this template to trigger rollout when the token changes.
# Any edit here forces a rolling update of the controller deployment.
# Keep it minimal: only include the agent token and required fields.
{{- if .Values.agent.token }}
apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  {{- with .Values.extraAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ .Values.agent.token | b64enc | quote }}
{{- end }}
