{{- if eq (include "datafy-agent.uninstallModeNormalized" .) "transparent" }}
apiVersion: v1
kind: ConfigMap
metadata:
  # This ConfigMap indicates to the controller that the chart is installed.
  # The controller should watch this ConfigMap for deletion.
  # When Helm uninstalls the chart, this resource will be deleted, which
  # should trigger the controller to edit its behavior accordingly.
  # ONLY for transparent uninstall mode.
  name: datafy-install-marker
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extraLabels }}
  labels:
  {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.extraAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
# ResourceAnchor is used as an ownerReference root;
# when Helm removes this resource, Kubernetes GC will cascade-delete all resources owned by it.
apiVersion: datafy.io/v1
kind: ResourceAnchor
metadata:
  name: datafy-ra
  {{- if eq (include "datafy-agent.uninstallModeNormalized" .) "transparent" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
