apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ required "ERROR: agent.token is required" .Values.agent.token | b64enc | quote }}
---
{{- if .Values.ebsCsiProxy.enabled }}
{{- if ne .Release.Namespace (include "datafy-agent.ebsCsiProxyNamespace" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ include "datafy-agent.ebsCsiProxyNamespace" . }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ .Values.agent.token | b64enc | quote }}
{{- end }}
{{- end }}
