apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datafy-agent
    {{- with .Values.extraLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.extraAnnotations }}{{ toYaml . | nindent 4 }}{{- end }}
type: Opaque
data:
  token: {{ required "ERROR: agent.token is required" .Values.agent.token | b64enc | quote }}
---
{{- if .Values.ebsCsiProxy.enabled }}
{{- if ne .Release.Namespace (include "ebsCsiProxyNamespace" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ include "ebsCsiProxyNamespace" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datafy-agent
    {{- with .Values.extraLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.extraAnnotations }}{{ toYaml . | nindent 4 }}{{- end }}
type: Opaque
data:
  token: {{ .Values.agent.token | b64enc | quote }}
{{- end }}
{{- end }}
