apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datafy-agent
    {{- with .Values.extraLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.extraAnnotations }}{{ toYaml . | nindent 4 }}{{- end }}
type: Opaque
data:
  token: {{ required "ERROR: .Values.datafy.token is required" .Values.datafy.token | b64enc | quote }}
---
{{- $csiNamespace := default "kube-system" .Values.csi.namespace }}
{{- if ne .Release.Namespace $csiNamespace }}
apiVersion: v1
kind: Secret
metadata:
  name: datafy-token
  namespace: {{ $csiNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datafy-agent
    {{- with .Values.extraLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    {{- with .Values.extraAnnotations }}{{ toYaml . | nindent 4 }}{{- end }}
type: Opaque
data:
  token: {{ required "ERROR: .Values.datafy.token is required" .Values.datafy.token | b64enc | quote }}
{{- end }}
