apiVersion: v1
kind: ConfigMap
metadata:
  name: datafy-volume-mapping
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extraLabels }}
  labels:
  {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.extraAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
