apiVersion: v1
kind: ConfigMap
metadata:
  name: datafy-volume-replacements
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "datafy-agent.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  {{- with .Values.extraAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  replacements: ""
