name: Check Chart Version

on:
  pull_request:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            helm:
              - 'templates/**'
              - 'files/**'
              - Chart.yaml
              - values.yaml

      - name: Base branch Chart.yaml version
        if: ${{ steps.changes.outputs.helm == 'true' }}
        id: base_version
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          BASE_VERSION=$(git show origin/${{ github.base_ref }}:Chart.yaml | grep '^version:' | awk '{print $2}')
          echo "BASE_VERSION=$BASE_VERSION" >> $GITHUB_ENV

      - name: PR branch Chart.yaml version
        if: ${{ steps.changes.outputs.helm == 'true' }}
        id: pr_version
        run: |
          PR_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV

      - name: Compare Versions
        if: ${{ steps.changes.outputs.helm == 'true' }}
        run: |
          if [ "${{ steps.changes.outputs.helm }}" = "true" ]; then
            if [ "$BASE_VERSION" = "$PR_VERSION" ]; then
              echo "❌ Chart version was not updated! Please update the version in Chart.yaml."
              exit 1
            else
              echo "✅ Chart version has been updated."
              exit 0
            fi
          else
            echo "✅ No need to update Chart version."
            exit 0
          fi 
          
