name: test Chart

on:
  push:

permissions:
  id-token: write
  contents: write  # Grant write access to the repository contents

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - name: Add required Helm repos
        run: |
          helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          helm repo update

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "changed=true" >> "$GITHUB_OUTPUT"
      #     fi

      - name: Run chart-testing (lint)
        # if: steps.list-changed.outputs.changed == 'true'
        # run: ct lint --target-branch ${{ github.event.repository.default_branch }}
        run: ct lint --chart-dirs . --config .ct.yaml --charts .

      - name: Create kind cluster
        # if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Install aws-ebs-csi-driver (may not become Ready in Kind)
        run: |
          helm install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
            --namespace kube-system \
            --set node.serviceAccount.create=true \
            --set node.serviceAccount.name=ebs-csi-node-sa \
            --set controller.serviceAccount.create=true \
            --set controller.serviceAccount.name=ebs-csi-controller-sa \
            --wait --timeout 5m

      # Correct rollout waits (resource names are *without* -sa)
      - name: Wait for controller rollout
        run: kubectl -n kube-system rollout status deployment/ebs-csi-controller --timeout=300s

      - name: Wait for node DaemonSet rollout
        run: kubectl -n kube-system rollout status daemonset/ebs-csi-node --timeout=300s
        
      - name: Run chart-testing (install)
        # if: steps.list-changed.outputs.changed == 'true'
        # run: ct install --target-branch ${{ github.event.repository.default_branch }}
        run: |
          ct install \
            --chart-dirs . \
            --config .ct.yaml \
            --charts . \
            --namespace test \
            --helm-extra-set-args '--debug --create-namespace --set agent.token=value1 --set awsEbsCsiDriver.enabled=false'
