name: test Chart

on:
  push:

permissions:
  id-token: write
  contents: write  # Grant write access to the repository contents

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: Sensor
            extraArgs: ""

          - mode: AutoScaler
            extraArgs: "--set awsEbsCsiDriver.enabled=true"

    name: Test (${{ matrix.mode }} with ${{ matrix.extraArgs }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - name: Add required Helm repos
        run: |
          helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          helm repo update

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "changed=true" >> "$GITHUB_OUTPUT"
      #     fi

      - name: Run chart-testing (lint)
        # if: steps.list-changed.outputs.changed == 'true'
        # run: ct lint --target-branch ${{ github.event.repository.default_branch }}
        run: ct lint --chart-dirs . --config .ct.yaml --charts .

      - name: Create kind cluster
        # if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      # - name: Fake AWS identity on kind nodes
      #   run: |
      #     for n in $(kubectl get nodes -o name); do
      #       kubectl label $n topology.kubernetes.io/region=us-east-1 --overwrite
      #       kubectl label $n topology.kubernetes.io/zone=us-east-1a --overwrite
      #       kubectl label $n node.kubernetes.io/instance-type=m5.large --overwrite
      #       kubectl patch $n --type merge -p '{"spec":{"providerID":"aws:///us-east-1a/i-1234567890abcdef0"}}'
      #     done

      # - name: Install AWS EBS CSI driver (kind patched)
      #   run: |
      #     helm install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
      #       --namespace kube-system \
      #       --create-namespace \
      #       --set node.serviceAccount.create=true \
      #       --set node.serviceAccount.name=ebs-csi-node-sa \
      #       --set node.extraArgs[0]=--metadata-sources=kubernetes \
      #       --set node.extraEnv[0].name=AWS_REGION \
      #       --set node.extraEnv[0].value=us-east-1 \
      #       --set controller.enabled=true \
      #       --set controller.serviceAccount.create=true \
      #       --set controller.serviceAccount.name=ebs-csi-controller-sa \
      #       --set controller.extraEnv[0].name=AWS_REGION \
      #       --set controller.extraEnv[0].value=us-east-1 \
      #       --timeout 5m
            
      - name: Run chart-testing (install)
        # if: steps.list-changed.outputs.changed == 'true'
        # run: ct install --target-branch ${{ github.event.repository.default_branch }}
        run: |
          ct install \
            --chart-dirs . \
            --config .ct.yaml \
            --charts . \
            --namespace test \
            --helm-extra-set-args "--debug --create-namespace  --set agent.token=${{ secrets.STGN_SECRET }} --set agent.mode=${{ matrix.mode }} ${{ matrix.extraArgs }}"
