name: test Chart

on:
  push:

permissions:
  id-token: write
  contents: write  # Grant write access to the repository contents

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: Sensor
            extraArgs: "--set ebsCsiProxy.enabled=false"

          - mode: AutoScaler
            extraArgs: ""

    name: Test (${{ matrix.mode }} with ${{ matrix.extraArgs }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - name: Add required Helm repos
        run: |
          helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          helm repo update

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "changed=true" >> "$GITHUB_OUTPUT"
      #     fi

      - name: Run chart-testing (lint)
        # if: steps.list-changed.outputs.changed == 'true'
        # run: ct lint --target-branch ${{ github.event.repository.default_branch }}
        run: ct lint --chart-dirs . --config .ct.yaml --charts .

      - name: Create kind cluster
        # if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Apply fake EBS CSI resources
        if: matrix.mode == 'AutoScaler'
        run: |
          set -euo pipefail
          cat <<'YAML' | kubectl apply -f -
          apiVersion: storage.k8s.io/v1
          kind: CSIDriver
          metadata:
            name: ebs.csi.aws.com
          spec:
            attachRequired: true
            podInfoOnMount: true
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ebs-csi-controller
            namespace: kube-system
            labels:
              app.kubernetes.io/name: ebs-csi-controller
              app.kubernetes.io/version: "v0.0.0-fake"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: ebs-csi-controller
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: ebs-csi-controller
                  app.kubernetes.io/version: "v0.0.0-fake"
              spec:
                containers:
                  - name: ebs-plugin
                    image: public.ecr.aws/docker/library/busybox:latest
                    command: ["sh","-c"]
                    args:
                      - |
                        mkdir -p /csi && mknod /csi/csi.sock p || true
                        while true; do sleep 3600; done
                    env:
                      - name: CSI_ENDPOINT
                        value: "unix:///csi/csi.sock"
                    volumeMounts:
                      - name: socket-dir
                        mountPath: /csi
                volumes:
                  - name: socket-dir
                    emptyDir: {}
          ---
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: ebs-csi-node
            namespace: kube-system
            labels:
              app.kubernetes.io/name: ebs-csi-node
              app.kubernetes.io/version: "v0.0.0-fake"
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: ebs-csi-node
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: ebs-csi-node
                  app.kubernetes.io/version: "v0.0.0-fake"
              spec:
                containers:
                  - name: ebs-plugin
                    image: public.ecr.aws/docker/library/busybox:latest
                    securityContext:
                      privileged: true
                      readOnlyRootFilesystem: false
                    command: ["sh","-c"]
                    args:
                      - |
                        mkdir -p /csi && mknod /csi/csi.sock p || true
                        while true; do sleep 3600; done
                    env:
                      - name: CSI_ENDPOINT
                        value: "unix:///csi/csi.sock"
                    volumeMounts:
                      - name: socket-dir
                        mountPath: /csi
                      - name: kubelet-dir
                        mountPath: /var/lib/kubelet
                        mountPropagation: Bidirectional
                      - name: device-dir
                        mountPath: /dev
                volumes:
                  - name: socket-dir
                    emptyDir: {}
                  - name: kubelet-dir
                    hostPath:
                      path: /var/lib/kubelet
                      type: Directory
                  - name: device-dir
                    hostPath:
                      path: /dev
                      type: Directory
          YAML

      # - name: Fake AWS identity on kind nodes
      #   if: matrix.extraArgs == '--set awsEbsCsiDriver.enabled=true'
      #   run: |
      #     for n in $(kubectl get nodes -o name); do
      #       kubectl label $n topology.kubernetes.io/region=us-east-1 --overwrite
      #       kubectl label $n topology.kubernetes.io/zone=us-east-1a --overwrite
      #       kubectl label $n node.kubernetes.io/instance-type=m5.large --overwrite
      #       kubectl patch $n --type merge -p '{"spec":{"providerID":"aws:///us-east-1a/i-1234567890abcdef0"}}'
      #     done

      # - name: Install AWS EBS CSI driver (kind patched)
      #   run: |
      #     helm install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
      #       --namespace kube-system \
      #       --create-namespace \
      #       --set node.serviceAccount.create=true \
      #       --set node.serviceAccount.name=ebs-csi-node-sa \
      #       --set node.extraArgs[0]=--metadata-sources=kubernetes \
      #       --set node.extraEnv[0].name=AWS_REGION \
      #       --set node.extraEnv[0].value=us-east-1 \
      #       --set controller.enabled=true \
      #       --set controller.serviceAccount.create=true \
      #       --set controller.serviceAccount.name=ebs-csi-controller-sa \
      #       --set controller.extraEnv[0].name=AWS_REGION \
      #       --set controller.extraEnv[0].value=us-east-1 \
      #       --timeout 5m
            
      - name: Run chart-testing (install)
        # if: steps.list-changed.outputs.changed == 'true'
        # run: ct install --target-branch ${{ github.event.repository.default_branch }}
        run: |
          ct install \
            --chart-dirs . \
            --config .ct.yaml \
            --charts . \
            --namespace test \
            --helm-extra-set-args "--debug --create-namespace --timeout 5m --set agent.token=${{ secrets.STGN_SECRET }} --set agent.mode=${{ matrix.mode }} ${{ matrix.extraArgs }}"
