name: Update AWS EBS CSI Driver Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day

permissions:
  id-token: write
  contents: write

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    outputs:
      VERSION_CHANGE_DETECTED: ${{ steps.version-changed.outputs.VERSION_CHANGE_DETECTED }}
    steps:
      - uses: actions/checkout@v4
      - name: Get latest version of aws-ebs-csi-driver
        run: |
          helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          helm repo update
          
          LATEST_VERSION=$(helm search repo aws-ebs-csi-driver --versions | grep "aws-ebs-csi-driver" | head -n 1 | awk '{print $2}')
          echo "EBS_CSI_DRIVER_NEW_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
      - name: Get current aws-ebs-csi-driver version from Chart.yaml
        run: |
          CURRENT_VERSION=$(yq '.dependencies[] | select(.name == "aws-ebs-csi-driver") | .version' Chart.yaml)
          echo "EBS_CSI_DRIVER_CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - name: Check if the version has changed
        id: version-changed
        run: |
          if [[ "${{ env.EBS_CSI_DRIVER_NEW_VERSION }}" == "${{ env.EBS_CSI_DRIVER_CURRENT_VERSION }}" ]]; then
            echo "No version change detected."
            echo "VERSION_CHANGE_DETECTED=false" >> "$GITHUB_OUTPUT"
          else
            echo "Version change detected."
            echo "VERSION_CHANGE_DETECTED=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Update Chart.yaml with aws-ebs-csi-driver version
        if: steps.version-changed.outputs.VERSION_CHANGE_DETECTED == 'true'
        run: |
          yq -i '.dependencies[] |= (select(.name == "aws-ebs-csi-driver") .version = "${{ env.EBS_CSI_DRIVER_NEW_VERSION }}")' Chart.yaml
      - name: Update Helm dependency
        run: |
          helm dependency update

      - name: Setup access to github
        if: steps.version-changed.outputs.VERSION_CHANGE_DETECTED == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          echo "machine github.com login ${{ vars.GH_ACCESS_USERNAME }} password ${{ secrets.GH_ACCESS_TOKEN }}" >> ~/.netrc
          echo "machine api.github.com login ${{ vars.GH_ACCESS_USERNAME }} password ${{ secrets.GH_ACCESS_TOKEN }}" >> ~/.netrc
      - name: Commit changes to Chart.yaml
        if: steps.version-changed.outputs.VERSION_CHANGE_DETECTED == 'true'
        run: |
          git add Chart.yaml Chart.lock
          git commit -m "Update aws-ebs-csi-driver dependency to ${{ env.EBS_CSI_DRIVER_NEW_VERSION }}"
          git push

  datafy-incp-pr:
    needs: [ update-dependency ]
    if: needs.update-dependency.outputs.VERSION_CHANGE_DETECTED == 'true'
    uses: ./.github/workflows/release.yaml
    secrets:
      PRODUCTION_AWS_ROLE_ARN: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
